LOGO = """
XXXXXXXXXXXXXXXXXXXXXXXXXXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXAAXXXX
sXsXXXXXXXXXXXXXXXXXXXXXXXAXAAXAAXAAAAAAXAXXXXXXXAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXAAX
XXXXXXXXXXAAAAAAAAXXAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXssssXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXA
AAAAAAXXXXAAAXXXXXXXXXXXXXXXXXXXXXXXXsXXXXXXssssssssssssssXXXssXXXXXXXXsXXXXsXssXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
AAAAAAAXXXAXXXXXXXXXXXXXXXXXXXssssssssssXXXXXXXXXXXXssssssssssssssXXXXXXXXXssXXXssXXssXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
AAAAAAAXXXXXXXXAAAAAAAAAAAAAAXXXXXssssssssssssssXXXXXXXXXXsssssssssssssssssXXXXXssXsssXXXXXXXXXsXXXXXXXXXXXXXXXXXXXXXXX
AAAAAAXXXXXXXXXrrrrsssXXXXXAAAAAAAAAAAAAXXXXsssssXXXXXXXXXXsssssssssssssssssssssssXsXXXXXssssssssssXXXXXXXXXXXXXXXXXXXX
AAAAAXXXXXXXXXX::::::~:;:;;;;iiiirrrsssXXXAAAAAAXXXXXXXXXXXXsXXXsssssssssssssssssssssssssssssssssssssXXXXXXXXXXXXXXXXXX
AAAAAXXXXXXXXXX::;;::::;;:~:::~~~::~,   ..,,~~:sAXAAAAAXXAAAAAAAAAXXXXssssssssssssssssssssXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
AAAAAXXXAXAXXAX::;;;;::;:;::;i:::i;;:~         :XAAAAAAi.,~~~:;;iirrsXXXXXXAXXXXXXXXXXXXXXXXXXMODERN LIFE IS WARXXXXXXX
AAAAAXXXXXXXXXX;;;ii;;;;;:;;;;;:~:;;;:~.       :XXAAAXA; ::          ..~sAAAXXXAiiirrrsXXXXXXXXXXXssssXXXXXXXXXXXXXXXXX
AAAAAXXXXXXXXXX:::;:::::;;;::::~~~~::;i;:~...  :XAAAAXA;,;i:,,,~:~~~~~~:rAAXXssA,     :AAAX;;rrisXAXXXsXXXXXXXXXAAAAXXA
AAAAXXXXXXXXXXX;:::::::::;:::::;;:::~;;;:::~~~~:XAAAAAAr:;;;;;;;::::;;::rAAssssX:~~,,,:AAAX;;r:.;XXXXr,rXsrsXXAXXAXXAAX
AAAAXXXXXXXXXAX:::::;;;:ii;i;ii;:::;:;;::;;:::~:XAAAAAAsi;;;;;;;;:::;;;:rAXXsrsX;::::::AAAs:;rr;rXXXXXXXXXXXsssrsXrrXXr
AAAAXXXXXXXXXAX:;;iiii;;;r;;i;;~:;;;::;::;::;::;AAAAAAAri;;;;;;ii;;;;:;:sAXriiXX:;iirirAXAXsXXXssXXXXi~:X;;i;rXsrs;rXsr
AAAAXXXXAXXXXXXiiiiiiiri;iiiii;:;i;;;::;;::::~~;AAAAAAAr;rririiriiiiiiiisXXsssXXsssssAXAAAsi;ri:iXXssr;isrrsrAAAAXXXAXs
AAAAXXsXXXXXXXsi;;ii;;iiririir;;iiiii;i;;:::::~;AAAAAAAsrssrsssssssssssssXXssrXXrrrrrsXXAAXXXXXAAAAXXAAAAAAAAAAAAAAAAAX
AAAAAXXXXXXXXXs;;:;ii;;ii;i;;;:;;;iiiiiirrrrrrirXXXAAAAAAXXXsXsssssssXsssXXriiXXXXAAXXAAAAXXAAAAAAAAAAAAAAAAAAAAXXXXXXX
AAAAAAXXXXXXXXsiiirrrrrrirrrrrrsssssssssXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXsssrrissssssXAAAAAXAAAAAAAAAXXXXXXXsssXXsssssss
AAAAAAXXAXXXXXXXXXXXXXXXXXXXXAXXXXXXXXXAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXsrXsrssssssssssXXXXXssXXXsrrrrrsssrrrrrrrssssss
AAAAAAAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXAXXAAAAAArsXrrssssrXAAAAXsXXs;iiiiiiirrrrrrrrrrsssssssss
AAAAAAAXXXXAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXAAAAAAAAAXXXXsssrrriiir;ir;;;;iXAAAAXsXXsiiiiiirrrrrrrrrrsssssssssss
AAAAAAAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXAAAAAAAAAAXXXXssssrrrrriiiiiiiii;irirriiiirXXXXXXsXXrirrrrrrrrrrrrssssssssssssss
AAAAAAAXXXXXXXXXXXXXXXXXAAXAAAAAAAAAAAXXXXsssrrriiiii;;;;;;iiiiiiiiiiiiirrrrsssssssssssssXXssssssssssssssssssssssssssss
AAAAAAAAXXXXXXAAAAAAAAAAAAAXXXXXsssrrrriiiii;;;;;;;;iiiiiiiiiiiiiiiiiiiirrrrrrsssssssXXXXXXXXXXXXXXXXXXssssssssssXXXXXX
AAAAAAAAXXXXXXAAAAAXXXXsssrrriiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiirrrirrrrrrrrrrrrrrssssssssssXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
AAAAAAAAAAAAXXXssssrrrrrriiiiiiiiiiiiiiiiiriiiiiiiiiirrrrrrrrrrrrrrrrrrrrrrrrrrrrsssssssssssssXXXXXXXXXXXXXXXXXXXXXXXXX
"""

DATA = "data"
SRTM = "srtm"
TILES = "tiles"

ADDR = ("0.0.0.0", 4443)
SAMPLES = 3601
NODATA = -9999
R = 6371.0

